on: push

jobs:
   typecheck:
      runs-on: ubuntu-latest
      steps:
         - name: Harden Runner
           uses: step-security/harden-runner@14dc64f30986eaa2ad2dddcec073f5aab18e5a24 # v1
           with:
             egress-policy: block
             allowed-endpoints: 
               github.com:443
               registry.yarnpkg.com:443

         - uses: actions/checkout@629c2de402a417ea7690ca6ce3f33229e27606a5 # v2
         - name: Setup Node.js environment
           uses: actions/setup-node@f099707f6e7a91b89cdebdeca599fc76cc8bf088
         - run: yarn --frozen
         - name: Typescript compiler
           uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069 # v1
         - run: yarn test
