on: push

jobs:
   typecheck:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@2d1c1198e79c30cca5c3957b1e3b65ce95b5356e
         - name: Setup Node.js environment
           uses: actions/setup-node@c2ac33f2c62f978d6c944d9648125a294e56dc0b
         - run: yarn --frozen
         - name: Typescript compiler
           uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069 # v1
         - run: yarn test
