on: push

jobs:
   typecheck:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
         - name: Setup Node.js environment
           uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
         - run: yarn --frozen
         - name: Typescript compiler
           uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069 # v1
         - run: yarn test
