on: push

jobs:
   typecheck:
      runs-on: ubuntu-latest
      steps:
         - name: Harden Runner
           uses: step-security/harden-runner@v1
           with:
             egress-policy: audit

         - uses: actions/checkout@v2
         - name: Setup Node.js environment
           uses: actions/setup-node@v2.1.5
         - run: yarn --frozen
         - name: Typescript compiler
           uses: iCrawl/action-tsc@v1
         - run: yarn test
