on: push

jobs:
   typecheck:
      runs-on: ubuntu-latest
      steps:
         - name: Harden Runner
           uses: step-security/harden-runner@4a1e83c9ef6b0e39b16f17b2734e08cdfbeea46c
           with:
             egress-policy: block
             allowed-endpoints: 
               github.com:443
               registry.yarnpkg.com:443

         - uses: actions/checkout@2d1c1198e79c30cca5c3957b1e3b65ce95b5356e
         - name: Setup Node.js environment
           uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
         - run: yarn --frozen
         - name: Typescript compiler
           uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069 # v1
         - run: yarn test
