on: push

jobs:
   typecheck:
      runs-on: ubuntu-latest
      steps:
         - name: Harden Runner
           uses: step-security/harden-runner@072ec3f66f8a16c9aed9a48249cb5b8b3b193d1e
           with:
             egress-policy: block
             allowed-endpoints: 
               github.com:443
               registry.yarnpkg.com:443

         - uses: actions/checkout@230611dbd0eb52da1e1f4f7bc8bb0c3a339fc8b7
         - name: Setup Node.js environment
           uses: actions/setup-node@9ced9a43a244f3ac94f13bfd896db8c8f30da67a
         - run: yarn --frozen
         - name: Typescript compiler
           uses: iCrawl/action-tsc@c3f25c126c7805dbbbcbf6f1db0c3be6f5dac069 # v1
         - run: yarn test
